config/routes.rb
MaeJurema::Application.routes.draw do
  get "home/index"

  get 'iniciar' => 'home#iniciar'

  post 'sim/:id'=> 'home#sim', :as => :sim

  post 'nao/:id'=> 'home#nao', :as => :nao
  
  resources :pessoas

  resources :perguntas

  root :to => 'home#index'

end

app/models/pergunta.rb
class Pergunta < ActiveRecord::Base
  attr_accessible :caracteristica, :pergunta
end

app/models/pessoa.rb
class Pessoa < ActiveRecord::Base
  attr_accessible :caracteristicas, :foto, :nome
  mount_uploader :foto, FotoUploader

  def self.com(caracteristicas)
  	Pessoa.all.each do |pessoa|
  		return pessoa if pessoa.caracteristicas.split(',').map(&:split).sort.join(',') == caracteristicas.sort.join(',')
  	end
  	nil
  end	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def iniciar
  	session[:caracteristicas] = []
  	Pergunta.update_all(resposta: '')
  	proxima_pergunta
  end

  def nao
  	pergunta = Pergunta.find(params[:id])
  	pergunta.resposta = 'n'
  	pergunta.save
  	proxima_pergunta
  end

  def sim
  	pergunta = Pergunta.find(params[:id])
  	pergunta.resposta = 's'
  	pergunta.save
  	session[:caracteristicas] << pergunta.caracteristica
  	pessoa = Pessoa.com(session[:caracteristicas])
  	if pessoa
  		@pessoa = pessoa
  		render :resultado
  	else
  		proxima_pergunta
  	end
  end

  private 

  def proxima_pergunta
  	@pergunta = Pergunta.where(resposta: '').first
  	if @pergunta.nil?
  		render :falha
  	else 
		render :pergunta
	end
  end
end

app/controllers/perguntas_controller.rb
class PerguntasController < ApplicationController
  # GET /perguntas
  # GET /perguntas.json
  def index
    @perguntas = Pergunta.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @perguntas }
    end
  end

  # GET /perguntas/1
  # GET /perguntas/1.json
  def show
    @pergunta = Pergunta.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pergunta }
    end
  end

  # GET /perguntas/new
  # GET /perguntas/new.json
  def new
    @pergunta = Pergunta.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pergunta }
    end
  end

  # GET /perguntas/1/edit
  def edit
    @pergunta = Pergunta.find(params[:id])
  end

  # POST /perguntas
  # POST /perguntas.json
  def create
    @pergunta = Pergunta.new(params[:pergunta])

    respond_to do |format|
      if @pergunta.save
        format.html { redirect_to @pergunta, notice: 'Pergunta was successfully created.' }
        format.json { render json: @pergunta, status: :created, location: @pergunta }
      else
        format.html { render action: "new" }
        format.json { render json: @pergunta.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /perguntas/1
  # PUT /perguntas/1.json
  def update
    @pergunta = Pergunta.find(params[:id])

    respond_to do |format|
      if @pergunta.update_attributes(params[:pergunta])
        format.html { redirect_to @pergunta, notice: 'Pergunta was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pergunta.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /perguntas/1
  # DELETE /perguntas/1.json
  def destroy
    @pergunta = Pergunta.find(params[:id])
    @pergunta.destroy

    respond_to do |format|
      format.html { redirect_to perguntas_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pessoas_controller.rb
class PessoasController < ApplicationController
  # GET /pessoas
  # GET /pessoas.json
  def index
    @pessoas = Pessoa.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pessoas }
    end
  end

  # GET /pessoas/1
  # GET /pessoas/1.json
  def show
    @pessoa = Pessoa.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pessoa }
    end
  end

  # GET /pessoas/new
  # GET /pessoas/new.json
  def new
    @pessoa = Pessoa.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pessoa }
    end
  end

  # GET /pessoas/1/edit
  def edit
    @pessoa = Pessoa.find(params[:id])
  end

  # POST /pessoas
  # POST /pessoas.json
  def create
    @pessoa = Pessoa.new(params[:pessoa])

    respond_to do |format|
      if @pessoa.save
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully created.' }
        format.json { render json: @pessoa, status: :created, location: @pessoa }
      else
        format.html { render action: "new" }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pessoas/1
  # PUT /pessoas/1.json
  def update
    @pessoa = Pessoa.find(params[:id])

    respond_to do |format|
      if @pessoa.update_attributes(params[:pessoa])
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pessoas/1
  # DELETE /pessoas/1.json
  def destroy
    @pessoa = Pessoa.find(params[:id])
    @pessoa.destroy

    respond_to do |format|
      format.html { redirect_to pessoas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/perguntas_helper.rb
module PerguntasHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/views/home/falha.html.erb
<h3>Não consegui adivinhar a pessoa... =(</h3>
<%= link_to 'Começar de novo',root_path %>

app/views/home/index.html.erb
<h1>
	Eu sou Mãe Jurema
</h1>
<h3>
	e eu posso adivinhar a pessoa amada em segundos!
</h3>
<p>
	Pense em uma pessoa e clique no link abaixo para iniciar. 
</p>
<%= link_to 'Iniciar', iniciar_path %>

app/views/home/pergunta.html.erb
<h3><%= @pergunta.pergunta %></h3>
<%= link_to image_tag('/assets/botao_sim.png'), sim_path(@pergunta), method: :post%>
<%= link_to image_tag('/assets/botao_nao.png'), nao_path(@pergunta), method: :post%>

app/views/home/resultado.html.erb
<h3>A pessoa que você pensou é: </h3>
<h1><%= @pessoa.nome %></h1>
<%= image_tag(@pessoa.foto_url) if @pessoa.foto.present? %>
<br />
<%= link_to 'Começar de novo', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MaeJurema</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/perguntas/_form.html.erb
<%= form_for(@pergunta) do |f| %>
  <% if @pergunta.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pergunta.errors.count, "error") %> prohibited this pergunta from being saved:</h2>

      <ul>
      <% @pergunta.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pergunta %><br />
    <%= f.text_field :pergunta %>
  </div>
  <div class="field">
    <%= f.label :caracteristica %><br />
    <%= f.text_field :caracteristica %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/perguntas/edit.html.erb
<h1>Editing pergunta</h1>

<%= render 'form' %>

<%= link_to 'Show', @pergunta %> |
<%= link_to 'Back', perguntas_path %>

app/views/perguntas/index.html.erb
<h1>Listing perguntas</h1>

<table>
  <tr>
    <th>Pergunta</th>
    <th>Caracteristica</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @perguntas.each do |pergunta| %>
  <tr>
    <td><%= pergunta.pergunta %></td>
    <td><%= pergunta.caracteristica %></td>
    <td><%= link_to 'Show', pergunta %></td>
    <td><%= link_to 'Edit', edit_pergunta_path(pergunta) %></td>
    <td><%= link_to 'Destroy', pergunta, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pergunta', new_pergunta_path %>

app/views/perguntas/new.html.erb
<h1>New pergunta</h1>

<%= render 'form' %>

<%= link_to 'Back', perguntas_path %>

app/views/perguntas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Pergunta:</b>
  <%= @pergunta.pergunta %>
</p>

<p>
  <b>Caracteristica:</b>
  <%= @pergunta.caracteristica %>
</p>


<%= link_to 'Edit', edit_pergunta_path(@pergunta) %> |
<%= link_to 'Back', perguntas_path %>

app/views/pessoas/_form.html.erb
<%= form_for(@pessoa) do |f| %>
  <% if @pessoa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pessoa.errors.count, "error") %> prohibited this pessoa from being saved:</h2>

      <ul>
      <% @pessoa.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :foto %><br />
    <%= f.file_field :foto %>
  </div>
  <div class="field">
    <%= f.label :caracteristicas %><br />
    <%= f.text_area :caracteristicas %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pessoas/edit.html.erb
<h1>Editing pessoa</h1>

<%= render 'form' %>

<%= link_to 'Show', @pessoa %> |
<%= link_to 'Back', pessoas_path %>

app/views/pessoas/index.html.erb
<h1>Listing pessoas</h1>

<table>
  <tr>
    <th>Nome</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pessoas.each do |pessoa| %>
  <tr>
    <td><%= pessoa.nome %></td>
    <td><%= link_to 'Show', pessoa %></td>
    <td><%= link_to 'Edit', edit_pessoa_path(pessoa) %></td>
    <td><%= link_to 'Destroy', pessoa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pessoa', new_pessoa_path %>

app/views/pessoas/new.html.erb
<h1>New pessoa</h1>

<%= render 'form' %>

<%= link_to 'Back', pessoas_path %>

app/views/pessoas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @pessoa.nome %>
</p>

<p>
  <b>Foto:</b>
  <%= image_tag(@pessoa.foto_url, :width => 600) if @pessoa.foto.present? %>
</p>

<p>
  <b>Caracteristicas:</b>
  <%= @pessoa.caracteristicas %>
</p>


<%= link_to 'Edit', edit_pessoa_path(@pessoa) %> |
<%= link_to 'Back', pessoas_path %>